[package]
name = "dcc-providers"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
dcc-core = { path = "../dcc-core" }
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process", "rt", "macros", "io-util", "sync"] }
uuid = { version = "1", features = ["v4"] }
