//! Provider-neutral skills: single source of truth in `.devcommandcenter/skills/`,
//! compiled to each agent's native format. This module owns the source CRUD and the
//! compiler. Claude target is a faithful copy (`.claude/skills/<name>/SKILL.md`);
//! the AGENTS.md target flattens skills into an idempotent, delimited block.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tauri::command;

use crate::{db_error, ApiResult};

/// Target agent the source skill compiles to.
pub const TARGET_CLAUDE: &str = "claude";
/// Covers Codex, Droid and the emerging cross-tool `AGENTS.md` standard.
pub const TARGET_AGENTS_MD: &str = "agents";
/// Gemini CLI reads `GEMINI.md` (same always-on model as AGENTS.md).
pub const TARGET_GEMINI: &str = "gemini";
/// Cursor reads `.cursor/rules/<name>.mdc` (one file per rule).
pub const TARGET_CURSOR: &str = "cursor";

const AGENTS_BLOCK_START: &str = "<!-- dcc:skills:start -->";
const AGENTS_BLOCK_END: &str = "<!-- dcc:skills:end -->";
const MANAGED_MARKER_FILE: &str = ".dcc-managed.json";

fn default_scope() -> String {
    "project".to_string()
}

/// Writes only when content differs — keeps compilation idempotent so recompiling
/// on every workspace switch does not churn file mtimes or trip file watchers.
fn write_if_changed(path: &Path, content: &str) -> std::io::Result<()> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == content {
            return Ok(());
        }
    }
    fs::write(path, content)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillRecord {
    pub name: String,
    pub description: String,
    #[serde(default)]
    pub body: String,
    #[serde(default)]
    pub target_agents: Vec<String>,
    #[serde(default)]
    pub disable_model_invocation: bool,
    #[serde(default = "default_scope")]
    pub scope: String,
}

/// Metadata persisted in the manifest (everything except the body, which lives in SKILL.md).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ManifestEntry {
    name: String,
    description: String,
    #[serde(default)]
    target_agents: Vec<String>,
    #[serde(default)]
    disable_model_invocation: bool,
    #[serde(default = "default_scope")]
    scope: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct Manifest {
    #[serde(default)]
    skills: Vec<ManifestEntry>,
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

fn skills_root(project_root: &str) -> PathBuf {
    Path::new(project_root)
        .join(".devcommandcenter")
        .join("skills")
}

fn manifest_path(project_root: &str) -> PathBuf {
    skills_root(project_root).join("skills.json")
}

fn skill_md_path(project_root: &str, name: &str) -> PathBuf {
    skills_root(project_root).join(name).join("SKILL.md")
}

// ---------------------------------------------------------------------------
// Pure helpers (unit-tested)
// ---------------------------------------------------------------------------

/// Skill names map to directory names and must be safe, lower-kebab slugs.
fn is_valid_skill_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() <= 64
        && name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Faithful Claude/Agent-SDK SKILL.md: frontmatter + body.
fn render_skill_md(name: &str, description: &str, body: &str) -> String {
    format!(
        "---\nname: {name}\ndescription: {description}\n---\n\n{body}\n",
        body = body.trim_end()
    )
}

/// Strips the leading frontmatter block, returning the body only.
fn extract_body(skill_md: &str) -> String {
    let trimmed = skill_md.trim_start_matches('\u{feff}');
    if let Some(rest) = trimmed.strip_prefix("---") {
        if let Some(end) = rest.find("\n---") {
            let after = &rest[end + 4..];
            return after.trim_start_matches(['\n', '\r']).trim_end().to_string();
        }
    }
    trimmed.trim().to_string()
}

/// The generated AGENTS.md content (without the start/end markers).
fn render_agents_inner(skills: &[SkillRecord]) -> String {
    let mut out = String::from(
        "## Skills (generated by Dev Command Center — do not edit by hand)\n",
    );
    for skill in skills {
        out.push_str(&format!(
            "\n### {name}\n{description}\n\n{body}\n",
            name = skill.name,
            description = skill.description.trim(),
            body = skill.body.trim()
        ));
    }
    out
}

/// Idempotently inserts/replaces the DCC block in an existing AGENTS.md, preserving
/// hand-written content. When `inner` is empty the block is removed entirely.
fn upsert_agents_block(existing: &str, inner: &str) -> String {
    let block = if inner.is_empty() {
        String::new()
    } else {
        format!("{AGENTS_BLOCK_START}\n{}\n{AGENTS_BLOCK_END}\n", inner.trim_end())
    };

    if let (Some(start), Some(end)) = (
        existing.find(AGENTS_BLOCK_START),
        existing.find(AGENTS_BLOCK_END),
    ) {
        if end >= start {
            let end = end + AGENTS_BLOCK_END.len();
            let before = existing[..start].trim_end();
            let after = existing[end..].trim_start();
            let mut result = String::new();
            if !before.is_empty() {
                result.push_str(before);
                result.push_str("\n\n");
            }
            result.push_str(block.trim_end());
            if !after.is_empty() {
                result.push_str("\n\n");
                result.push_str(after);
            }
            let result = result.trim().to_string();
            return if result.is_empty() {
                String::new()
            } else {
                format!("{result}\n")
            };
        }
    }

    if block.is_empty() {
        return existing.to_string();
    }
    let base = existing.trim_end();
    if base.is_empty() {
        block
    } else {
        format!("{base}\n\n{block}")
    }
}

/// Cursor rule: own frontmatter (`description`, `alwaysApply`) + body.
fn render_cursor_mdc(skill: &SkillRecord) -> String {
    format!(
        "---\ndescription: {desc}\nalwaysApply: false\n---\n\n{body}\n",
        desc = skill.description.trim(),
        body = skill.body.trim()
    )
}

/// Skills targeting `target`, excluding those hidden from model invocation
/// (always-on artifacts must not carry hidden skills).
fn skills_for_target(skills: &[SkillRecord], target: &str) -> Vec<SkillRecord> {
    skills
        .iter()
        .filter(|s| {
            !s.disable_model_invocation && s.target_agents.iter().any(|t| t == target)
        })
        .cloned()
        .collect()
}

// ---------------------------------------------------------------------------
// Source CRUD
// ---------------------------------------------------------------------------

fn read_manifest(project_root: &str) -> Manifest {
    let path = manifest_path(project_root);
    let Ok(raw) = fs::read_to_string(&path) else {
        return Manifest::default();
    };
    serde_json::from_str(&raw).unwrap_or_default()
}

fn write_manifest(project_root: &str, manifest: &Manifest) -> ApiResult<()> {
    let root = skills_root(project_root);
    fs::create_dir_all(&root).map_err(|e| db_error(format!("{}: {e}", root.display())))?;
    let raw = serde_json::to_string_pretty(manifest)
        .map_err(|e| db_error(format!("serialize manifest: {e}")))?;
    fs::write(manifest_path(project_root), raw)
        .map_err(|e| db_error(format!("write manifest: {e}")))?;
    Ok(())
}

fn load_skills(project_root: &str) -> Vec<SkillRecord> {
    let manifest = read_manifest(project_root);
    manifest
        .skills
        .into_iter()
        .map(|entry| {
            let body = fs::read_to_string(skill_md_path(project_root, &entry.name))
                .map(|raw| extract_body(&raw))
                .unwrap_or_default();
            SkillRecord {
                name: entry.name,
                description: entry.description,
                body,
                target_agents: entry.target_agents,
                disable_model_invocation: entry.disable_model_invocation,
                scope: entry.scope,
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Compiler
// ---------------------------------------------------------------------------

fn compile_skills(project_root: &str, target_root: &str) -> ApiResult<()> {
    let skills = load_skills(project_root);
    let target = Path::new(target_root);

    // --- Claude target: faithful copy into .claude/skills/<name>/SKILL.md ---
    let claude_root = target.join(".claude").join("skills");
    let claude_names: Vec<String> = skills
        .iter()
        .filter(|s| s.target_agents.iter().any(|t| t == TARGET_CLAUDE))
        .map(|s| s.name.clone())
        .collect();

    // Remove only skills DCC previously managed and that are now gone.
    let managed_path = claude_root.join(MANAGED_MARKER_FILE);
    let previous: Vec<String> = fs::read_to_string(&managed_path)
        .ok()
        .and_then(|raw| serde_json::from_str(&raw).ok())
        .unwrap_or_default();
    for stale in previous.iter().filter(|n| !claude_names.contains(n)) {
        let dir = claude_root.join(stale);
        if dir.exists() {
            let _ = fs::remove_dir_all(&dir);
        }
    }

    if !claude_names.is_empty() {
        fs::create_dir_all(&claude_root)
            .map_err(|e| db_error(format!("{}: {e}", claude_root.display())))?;
    }
    for skill in skills.iter().filter(|s| claude_names.contains(&s.name)) {
        let dir = claude_root.join(&skill.name);
        fs::create_dir_all(&dir).map_err(|e| db_error(format!("{}: {e}", dir.display())))?;
        let content = render_skill_md(&skill.name, &skill.description, &skill.body);
        write_if_changed(&dir.join("SKILL.md"), &content)
            .map_err(|e| db_error(format!("write SKILL.md: {e}")))?;
    }
    if claude_root.exists() {
        let raw = serde_json::to_string(&claude_names).unwrap_or_else(|_| "[]".to_string());
        let _ = write_if_changed(&managed_path, &raw);
    }

    // --- Always-on block targets: flatten (skip disabled-from-model skills) ---
    compile_block_file(target, "AGENTS.md", &skills_for_target(&skills, TARGET_AGENTS_MD))?;
    compile_block_file(target, "GEMINI.md", &skills_for_target(&skills, TARGET_GEMINI))?;

    // --- Cursor target: one .mdc rule per skill ---
    compile_cursor(target, &skills_for_target(&skills, TARGET_CURSOR))?;

    Ok(())
}

/// Regenerates the DCC block inside an always-on instructions file (AGENTS.md, GEMINI.md).
/// Removes the file if it ends up empty (no hand-written content left).
fn compile_block_file(
    target: &Path,
    file_name: &str,
    block_skills: &[SkillRecord],
) -> ApiResult<()> {
    let path = target.join(file_name);
    let existing = fs::read_to_string(&path).unwrap_or_default();
    let inner = if block_skills.is_empty() {
        String::new()
    } else {
        render_agents_inner(block_skills)
    };
    let next = upsert_agents_block(&existing, &inner);
    if next != existing {
        if next.trim().is_empty() {
            if path.exists() {
                let _ = fs::remove_file(&path);
            }
        } else {
            fs::write(&path, next)
                .map_err(|e| db_error(format!("write {file_name}: {e}")))?;
        }
    }
    Ok(())
}

/// Writes one `.cursor/rules/<name>.mdc` per skill, removing stale DCC-managed rules.
fn compile_cursor(target: &Path, cursor_skills: &[SkillRecord]) -> ApiResult<()> {
    let rules_dir = target.join(".cursor").join("rules");
    let names: Vec<String> = cursor_skills.iter().map(|s| s.name.clone()).collect();

    let managed_path = rules_dir.join(MANAGED_MARKER_FILE);
    let previous: Vec<String> = fs::read_to_string(&managed_path)
        .ok()
        .and_then(|raw| serde_json::from_str(&raw).ok())
        .unwrap_or_default();
    for stale in previous.iter().filter(|n| !names.contains(n)) {
        let file = rules_dir.join(format!("{stale}.mdc"));
        if file.exists() {
            let _ = fs::remove_file(&file);
        }
    }

    if !names.is_empty() {
        fs::create_dir_all(&rules_dir)
            .map_err(|e| db_error(format!("{}: {e}", rules_dir.display())))?;
    }
    for skill in cursor_skills {
        write_if_changed(
            &rules_dir.join(format!("{}.mdc", skill.name)),
            &render_cursor_mdc(skill),
        )
        .map_err(|e| db_error(format!("write cursor rule: {e}")))?;
    }
    if rules_dir.exists() {
        let raw = serde_json::to_string(&names).unwrap_or_else(|_| "[]".to_string());
        let _ = write_if_changed(&managed_path, &raw);
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Tauri commands
// ---------------------------------------------------------------------------

#[command]
pub fn skills_list(project_root: String) -> ApiResult<Vec<SkillRecord>> {
    Ok(load_skills(&project_root))
}

#[command]
pub fn skills_save(project_root: String, skill: SkillRecord) -> ApiResult<()> {
    if !is_valid_skill_name(&skill.name) {
        return Err(db_error(format!(
            "invalid skill name '{}': use lower-case letters, digits and hyphens",
            skill.name
        )));
    }

    let dir = skills_root(&project_root).join(&skill.name);
    fs::create_dir_all(&dir).map_err(|e| db_error(format!("{}: {e}", dir.display())))?;
    let content = render_skill_md(&skill.name, &skill.description, &skill.body);
    fs::write(dir.join("SKILL.md"), content)
        .map_err(|e| db_error(format!("write SKILL.md: {e}")))?;

    let mut manifest = read_manifest(&project_root);
    let entry = ManifestEntry {
        name: skill.name.clone(),
        description: skill.description,
        target_agents: skill.target_agents,
        disable_model_invocation: skill.disable_model_invocation,
        scope: skill.scope,
    };
    match manifest.skills.iter_mut().find(|e| e.name == skill.name) {
        Some(existing) => *existing = entry,
        None => manifest.skills.push(entry),
    }
    write_manifest(&project_root, &manifest)
}

#[command]
pub fn skills_delete(project_root: String, name: String) -> ApiResult<()> {
    let dir = skills_root(&project_root).join(&name);
    if dir.exists() {
        fs::remove_dir_all(&dir).map_err(|e| db_error(format!("{}: {e}", dir.display())))?;
    }
    let mut manifest = read_manifest(&project_root);
    manifest.skills.retain(|e| e.name != name);
    write_manifest(&project_root, &manifest)
}

#[command]
pub fn skills_compile(project_root: String, target_root: String) -> ApiResult<()> {
    compile_skills(&project_root, &target_root)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn skill(name: &str, targets: &[&str]) -> SkillRecord {
        SkillRecord {
            name: name.to_string(),
            description: format!("desc for {name}"),
            body: format!("Body of {name}."),
            target_agents: targets.iter().map(|s| s.to_string()).collect(),
            disable_model_invocation: false,
            scope: "project".to_string(),
        }
    }

    #[test]
    fn validates_skill_names() {
        assert!(is_valid_skill_name("revisar-pr"));
        assert!(is_valid_skill_name("skill1"));
        assert!(!is_valid_skill_name("Revisar"));
        assert!(!is_valid_skill_name("-leading"));
        assert!(!is_valid_skill_name("has space"));
        assert!(!is_valid_skill_name(""));
        assert!(!is_valid_skill_name("../escape"));
    }

    #[test]
    fn renders_and_round_trips_body() {
        let md = render_skill_md("foo", "does foo", "Line one.\nLine two.");
        assert!(md.starts_with("---\nname: foo\ndescription: does foo\n---\n"));
        assert_eq!(extract_body(&md), "Line one.\nLine two.");
    }

    #[test]
    fn extract_body_without_frontmatter() {
        assert_eq!(extract_body("just a body"), "just a body");
    }

    #[test]
    fn inserts_agents_block_preserving_handwritten() {
        let existing = "# AGENTS\n\nHand written rules.\n";
        let inner = render_agents_inner(&[skill("a", &[TARGET_AGENTS_MD])]);
        let out = upsert_agents_block(existing, &inner);
        assert!(out.contains("Hand written rules."));
        assert!(out.contains(AGENTS_BLOCK_START));
        assert!(out.contains("### a"));
        assert!(out.contains(AGENTS_BLOCK_END));
    }

    #[test]
    fn replaces_block_idempotently() {
        let existing = "Top.\n";
        let first = upsert_agents_block(&existing, &render_agents_inner(&[skill("a", &[TARGET_AGENTS_MD])]));
        let second = upsert_agents_block(&first, &render_agents_inner(&[skill("a", &[TARGET_AGENTS_MD])]));
        assert_eq!(first, second, "recompiling the same skills must be stable");
        assert_eq!(first.matches(AGENTS_BLOCK_START).count(), 1);
    }

    #[test]
    fn renders_cursor_mdc_with_frontmatter() {
        let mdc = render_cursor_mdc(&skill("review-pr", &[TARGET_CURSOR]));
        assert!(mdc.starts_with("---\ndescription: desc for review-pr\nalwaysApply: false\n---\n"));
        assert!(mdc.contains("Body of review-pr."));
    }

    #[test]
    fn skills_for_target_excludes_disabled() {
        let mut hidden = skill("hidden", &[TARGET_AGENTS_MD, TARGET_GEMINI]);
        hidden.disable_model_invocation = true;
        let visible = skill("visible", &[TARGET_GEMINI]);
        let all = vec![hidden, visible];
        let gemini = skills_for_target(&all, TARGET_GEMINI);
        assert_eq!(gemini.len(), 1);
        assert_eq!(gemini[0].name, "visible");
    }

    #[test]
    fn empty_inner_removes_block_keeps_handwritten() {
        let existing = "# AGENTS\n\nKeep me.\n";
        let with = upsert_agents_block(existing, &render_agents_inner(&[skill("a", &[TARGET_AGENTS_MD])]));
        let without = upsert_agents_block(&with, "");
        assert!(!without.contains(AGENTS_BLOCK_START));
        assert!(without.contains("Keep me."));
    }
}
